apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-project
  namespace: production
  labels:
    app: eks-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-project
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: eks-project
    spec:
      containers:
      - name: eks-project
        image: 720553587530.dkr.ecr.us-east-1.amazonaws.com/eks-app:1.0.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - eks-project
              topologyKey: kubernetes.io/hostname
